services:
  - type: web
    name: chatwithpdfs
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend.py --server.address 0.0.0.0 --server.port $PORT
